// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _2026_peminjamanruang_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RuangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RuangId");

                    b.ToTable("Peminjaman");
                });

            modelBuilder.Entity("Backend.Models.Ruang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ruang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            Name = "D3 Teather"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 500,
                            Name = "Auditorium Pasca Lt.6"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Name = "Ruang Rapat Pasca Lt.1"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 120,
                            Name = "Mini Teather Pasca Lt.6"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 300,
                            Name = "Hall D4"
                        });
                });

            modelBuilder.Entity("Backend.Models.Peminjaman", b =>
                {
                    b.HasOne("Backend.Models.Ruang", "Ruang")
                        .WithMany()
                        .HasForeignKey("RuangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruang");
                });
#pragma warning restore 612, 618
        }
    }
}
